### ISSUE TITLE
我觉得还可以扩展方法

### ISSUE THREAD

**Issue by rockjing** [houbb/lombok-ex#3]
亲，
可否写一个扩展方法的样例出来？
类似增加一个 toString， toJson 的方法之类？

**Comment by houbb** [comment]
可以的，不过最近加班比较多，没时间写。后面有时间写一下哈~~

**Comment by houbb** [comment]
[@ToString 方法拓展](https://github.com/houbb/lombok-ex#tostring-%E6%B3%A8%E8%A7%A3)，可供参考。
